#!/bin/bash

echo "input file name"
read filename

echo "enter command"
read userinput

echo "#!/bin/bash" > ${filename}
echo " ${userinput}"  > ${filename}

chmod +x ${filename}

echo "input commit message"
read var
echo "${var}" 



git add .
git commit -m "${var}"
git push
